src/VicentGodella/OpenGestia/OpenGestiaBundle/Entity/Ninyo.php
<?php

namespace VicentGodella\OpenGestia\OpenGestiaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use VicentGodella\OpenGestia\OpenGestiaBundle\Validator\Constraints as OpenGestiaAssert;

/**
 * VicentGodella\OpenGestiaBundle\Entity\Ninyo
 *
 * @ORM\Entity(repositoryClass="VicentGodella\OpenGestia\OpenGestiaBundle\Entity\NinyoRepository")
 */
class Ninyo extends Persona implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

	/**
	 * @ORM\Column(name="cuotaPagada", type="boolean")
	 */
	protected $cuotaPagada = false;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

	public function getTipoPersona()
	{
		return 'niño';
	}

	public function setCuotaPagada($cuotaPagada)
	{
		$this->cuotaPagada = $cuotaPagada;
	}

	public function getCuotaPagada()
	{
		return $this->cuotaPagada;
	}

}

src/VicentGodella/OpenGestia/OpenGestiaBundle/Controller/DefaultController.php
<?php

namespace VicentGodella\OpenGestia\OpenGestiaBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;


class DefaultController extends Controller
{
    public function indexAction()
    {
	    return new RedirectResponse('ninyo');
    }
}

src/VicentGodella/OpenGestia/OpenGestiaBundle/Resources/views/Default/buscar_persona.html.twig
{% extends '::base.html.twig' %}

{% block body %}
<form action="{{ path('buscar_persona') }}" method="POST">
	<table>
		<tr>
			<td colspan="2">
				{{ form_errors(formulario) }}
			</td>
		</tr>
		{% for key, field in formulario %}
			{% if key != '_token' %}
				<tr>
					<td colspan="2">
						{% if form_errors(field) | length > 0 %}
							<div class="error error-{{ key }}">
							{{ form_errors(field) }}
							</div>
						{% endif %}
					</td>
				</tr>
				<tr>
					<td>{{ form_label(field) }}</td>
					<td>{{ form_widget(field) }}</td>
				</tr>
			{% endif %}
		{% endfor %}
	</table>
	{{ form_rest(formulario)}}
	<input type="submit" value="Buscar" />
</form>
{% endblock %}

src/VicentGodella/OpenGestia/OpenGestiaBundle/Resources/views/Default/index.html.twig
{{ app.user.nombre }} {{ app.user.email }}

src/VicentGodella/OpenGestia/OpenGestiaBundle/Resources/views/Default/menu_seccion.html.twig
{% set active_section = active_section | default('ninyos') %}
<nav id="section-nav">
	<ul>
		<li id="ninyos-menu"  class="{% if active_section == 'ninyos' %}active{% endif %}">
			<a href="{{ url('ninyo_index') }}">Niños</a>

			<ul class="drop_down_options">
				<li><a href="{{ url('ninyo_index') }}">Listado general</a></li>
				<li><a class="baja-temporal" href="{{ url('ninyo_bajas') }}">Baja temporal</a></li>
				<li><a class="baja-definitiva" href="{{ url('ninyo_bajas_definitivas') }}">Baja definitiva</a></li>
			</ul>
		</li>
		<li id="educadores-menu" class="{% if active_section == 'educadores' %}active{% endif %}">
			<a href="{{ url('educador_index') }}">Educadores</a>

			<ul class="drop_down_options">
				<li><a href="{{ url('educador_index') }}">Listado general</a></li>
				<li><a class="baja-temporal" href="{{ url('educador_bajas') }}">Baja temporal</a></li>
				<li><a class="baja-definitiva" href="{{ url('educador_bajas_definitivas') }}">Baja definitiva</a></li>
			</ul>

		</li>
		<li class="{% if active_section == 'grupos' %}active{% endif %}">
			<a href="{{ url('grupo_index') }}">Grupos</a>
		</li>
	</ul>

	<div class="perfil-usuario">
		<a href="{{ url('_logout' )}}">Salir</a>
	</div>
</nav>

{#<nav>#}
	{#<ul>#}
		{#<li>#}
			{#<ul>#}
				{#Niños#}
				{#<li><a href="{{ url('ninyo_index') }}">Activos</a></li>#}
				{#<li><a href="{{ url('ninyo_bajas') }}">Bajas</a></li>#}
				{#<li><a href="{{ url('ninyo_bajas_definitivas') }}">Bajas Definitivas</a></li>#}
			{#</ul>#}
		{#</li>#}
		{#<li>#}
			{#<ul>#}
				{#Educadores#}
				{#<li><a href="{{ url('educador_index') }}">Activos</a></li>#}
				{#<li><a href="{{ url('educador_bajas') }}">Bajas</a></li>#}
				{#<li><a href="{{ url('educador_bajas_definitivas') }}">Bajas Definitivas</a></li>#}
			{#</ul>#}
		{#</li>#}
	{#</ul>#}

{#</nav>#}

src/VicentGodella/OpenGestia/OpenGestiaBundle/Resources/views/Default/resultados_buscar_persona.html.twig
{% extends '::base.html.twig' %}

{% block body %}

{% if app.session.hasFlash('notice') %}
<div class="flash-notice">
	{{ app.session.flash('notice') }}
</div>
{% endif %}

<table class="sortable-table">
	<thead>
	<tr>
		<th class="campo-nombre">Nombre</th>
		<th class="campo-apellidos">Apellidos</th>
		<th class="campo-poblacion">Población</th>
		<th class="campo-tipo">Tipo</th>

		<th>Acciones</th>
	</tr>
	</thead>
	<tbody>
	{% for persona in personas %}
	<tr class="persona">
		<td>{{ persona.nombre }}</td>
		<td>{{ persona.apellidos }}</td>
		<td>{{ persona.poblacion }}</td>
		<td>{{ persona.tipoPersona | capitalize }}</td>
		<td></td>
	</tr>
	{% endfor %}
	</tbody>
</table>
{% endblock %}

src/VicentGodella/OpenGestia/OpenGestiaBundle/Resources/views/Default/secciones.html.twig
<nav id="sections">
	<ul>
		<li class="active"><p>Secretaria</p></li>
		<li><p>Tresoreria</p></li>
		<li><p>Oficina Diocesana</p></li>
		<li><p>JEA</p></li>
	</ul>
</nav>